/* DSblock model generated by Dymola from Modelica model FastBuildings.Examples.SingleZone_Design
 Dymola Version 2017 FD01 (32-bit), 2016-10-11 translated this at Thu Mar 16 09:36:04 2017

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    1
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    18
#define NP_    8
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 2111717292
#define NHash2_ 520401687
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    22
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="FastBuildings.Examples.SingleZone_Design";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/u0110910/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 1;
DYNX(W_,4) = 1;
DYNX(W_,7) = 0;
DYNX(W_,14) = 0;
DYNX(W_,3) = 0.0;
DYNX(W_,11) = 0.0;
DYNX(W_,1) = 0;
DYNX(W_,2) = 0;
DYNX(W_,15) = 0.0;
DYNX(W_,10) = 0.0;
#endif
BoundParameterSection
DYNX(W_,8) = DYNX(DP_,2);
DYNX(W_,13) = DYNX(DP_,3);
DYNX(W_,16) = DYNX(DP_,2);
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(X_,0) = DYNX(DP_,4);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(X_,0) = DYNX(DP_,4);
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,17) = divmacro(DYNX(W_,16)*(DYNX(DP_,1)-DYNX(X_,0)),"bui.hva.cZon*(simFasBui.TSetDes-bui.zon.capZon.heaPor.T)",
  DYNX(DP_,7),"bui.hva.tauHea");
DYNX(W_,5) = (1-DYNX(DP_,6))*DYNX(W_,17);
DYNX(W_,6) = DYNX(DP_,6)*DYNX(W_,17);
 /* Linear system of equations to solve. */
DYNX(W_,12) = RememberSimple_(DYNX(W_,12), 0);
SolveScalarLinearParametric(DYNX(W_,13),"bui.zon.resWal.r", DYNX(DP_,0)-
  DYNX(X_,0),"simFasBui.TAmbDes-bui.zon.capZon.heaPor.T", DYNX(W_,12),
  "bui.zon.resWal.heaPor_a.Q_flow");
 /* End of Equation Block */ 

DYNX(W_,9) = DYNX(W_,5)+DYNX(W_,6)+DYNX(W_,12);
 /* Linear system of equations to solve. */
DYNX(F_,0) = RememberSimple_(DYNX(F_,0), 1);
SolveScalarLinearParametric(DYNX(W_,8),"bui.zon.capZon.c", DYNX(W_,9),
  "bui.zon.capZon.heaPor.Q_flow", DYNX(F_,0),"der(bui.zon.capZon.heaPor.T)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("simFasBui.nIrr", "Number of irradiation vectors [:#(type=Integer)]",\
 1, 1.0,1E+100,0.0,0,517)
DeclareAlias2("simFasBui.TAmb", "Ambient temperature [K]", "simFasBui.TAmbDes", 1,\
 7, 0, 0)
DeclareVariable("simFasBui.qHeaCoo", "Heating/cooling", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("simFasBui.powEle", "Electricity consumption", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("simFasBui.TSet", "Zone temperature set point [K]", \
"simFasBui.TSetDes", 1, 7, 1, 0)
DeclareVariable("simFasBui.irr[1]", "Array with irradiation inputs", 0.0, \
0.0,0.0,0.0,0,513)
DeclareParameter("simFasBui.TAmbDes", "Design ambient temperature [K|degC]", 0, \
263.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("simFasBui.TSetDes", "Design indoor temperature [K|degC]", 1, \
294.15, 0.0,1E+100,300.0,0,560)
DeclareVariable("bui.zon.nIrr", "Number of irradiation inputs/windows [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareAlias2("bui.zon.heaPorCon.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareVariable("bui.zon.heaPorCon.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("bui.zon.heaPorRad.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareVariable("bui.zon.heaPorRad.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("bui.zon.heaPorEmb.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareVariable("bui.zon.heaPorEmb.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("bui.zon.TZon", "Zone temperature. Most often this will be air temperature [K]",\
 "bui.zon.capZon.heaPor.T", 1, 1, 0, 0)
DeclareParameter("bui.zon.cZon", "Thermal capacity of the zone [J/K]", 2, \
10000000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("bui.zon.rWal", "Total thermal resistance of the walls, in K/W [K/W]",\
 3, 0.005, 0.0,0.0,0.0,0,560)
DeclareVariable("bui.zon.capZon.c", "Heat capacity of element (= cp*m) [J/K]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("bui.zon.capZon.TSta", "Initial temperature for the capacity, fixed=true [K|degC]",\
 4, 293.15, 0.0,1E+100,300.0,0,560)
DeclareState("bui.zon.capZon.heaPor.T", "Port temperature [K|degC]", 0, 0.0, 0.0,\
1E+100,300.0,0,552)
DeclareDerivative("bui.zon.capZon.heaPor.der(T)", "der(Port temperature) [K/s]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("bui.zon.capZon.heaPor.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("bui.zon.win[1].irr", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("bui.zon.win[1].heaPor1.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareVariable("bui.zon.win[1].heaPor1.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("bui.zon.win[1].gA", "gA value of the window(s)", 5, 1, \
0.0,0.0,0.0,0,560)
DeclareAlias2("bui.zon.resWal.heaPor_a.T", "Port temperature [K|degC]", \
"simFasBui.TAmbDes", 1, 7, 0, 4)
DeclareVariable("bui.zon.resWal.heaPor_a.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("bui.zon.resWal.heaPor_b.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareAlias2("bui.zon.resWal.heaPor_b.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "bui.zon.resWal.heaPor_a.Q_flow", -1, 5, 12, 132)
DeclareVariable("bui.zon.resWal.r", "Constant thermal resistance [K/W]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("bui.zon.preTAmb.port.T", "Port temperature [K|degC]", \
"simFasBui.TAmbDes", 1, 7, 0, 1028)
DeclareAlias2("bui.zon.preTAmb.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "bui.zon.resWal.heaPor_a.Q_flow", -1, 5, 12, 1156)
DeclareAlias2("bui.zon.preTAmb.T", "[K]", "simFasBui.TAmbDes", 1, 7, 0, 1024)
DeclareAlias2("bui.zon.senTZon.T", "Absolute temperature as output signal [K]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 1024)
DeclareAlias2("bui.zon.senTZon.port.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 1028)
DeclareVariable("bui.zon.senTZon.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0, 0.0,0.0,0.0,0,2825)
DeclareAlias2("bui.hva.TZon", "[K]", "bui.zon.capZon.heaPor.T", 1, 1, 0, 0)
DeclareAlias2("bui.hva.heaPorRad.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareAlias2("bui.hva.heaPorRad.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "bui.zon.heaPorRad.Q_flow", -1, 5, 6, 132)
DeclareAlias2("bui.hva.heaPorCon.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareAlias2("bui.hva.heaPorCon.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "bui.zon.heaPorCon.Q_flow", -1, 5, 5, 132)
DeclareAlias2("bui.hva.heaPorEmb.T", "Port temperature [K|degC]", \
"bui.zon.capZon.heaPor.T", 1, 1, 0, 4)
DeclareVariable("bui.hva.heaPorEmb.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("bui.hva.fraRad", "Fraction of heating to radiation [1]", 6, \
0.3, 0.0,0.0,0.0,0,560)
DeclareVariable("bui.hva.cZon", "Capacity of the zone [J/K]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("bui.hva.tauHea", "Time constant of the ideal heating [s]", 7, 1,\
 0.0,0.0,0.0,0,560)
DeclareVariable("bui.hva.qHeaCoo", "Total heating power [W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("bui.hva.TSet", "[K]", "simFasBui.TSetDes", 1, 7, 1, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,12), 0.0, 0);
DoRemember_(DYNX(F_,0), 0.0, 1);
EndEqBlock
EndDataBlock
